# Generated by Django 4.1.7 on 2023-03-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_categorie_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at', '-price', 'price']},
        ),
    ]
