# Generated by Django 4.1.7 on 2023-03-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_singleproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'ordering': ['name']},
        ),
    ]
