# Generated by Django 4.1.7 on 2023-03-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'ordering': ['first_name']},
        ),
    ]
