# Generated by Django 4.1.7 on 2023-03-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_aboutme_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='About',
        ),
    ]
