# Generated by Django 4.1.7 on 2023-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_aboutme_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
